### ISSUE TITLE
lcnc rip will not start

### ISSUE THREAD

**Issue by grotius-cnc** [phillc54/qtplasmac#1]
Hi Phill,

I cloned the repro and start it with a lcnc rip install. It's not starting. Pointing to line 700-714 qtplasmac_handler.py outcommenting some parts had no luck.

Here is the error :
`Traceback (most recent call last):
  File "/home/user/linux1/bin/qtvcp", line 381, in <module>
    APP = QTVCP()
  File "/home/user/linux1/bin/qtvcp", line 212, in __init__
    window.load_extension(opts.usermod)
  File "/home/user/linux1/lib/python/qtvcp/qt_makegui.py", line 250, in load_extension
    methods,self.handler_module,self.handler_instance = self._load_handlers([handlerpath], self.halcomp,self)
  File "/home/user/linux1/lib/python/qtvcp/qt_makegui.py", line 278, in _load_handlers
    mod = __import__(basename)
  File "qtplasmac/qtplasmac_handler.py", line 710
    def gcodes_changed(self, obj, cod):
    ^
IndentationError: expected an indented block
`

**Comment by rodw-au** [comment]
Hmm I cloned tonight and got past this. SO it must have been fixed in the last commit

**Comment by phillc54** [comment]
Yes, I think I do recall that one.
