### ISSUE TITLE
Disable RS485 and Do not show on main screen

### ISSUE THREAD

**Issue by rodw-au** [phillc54/qtplasmac#12]
How can  RS485 be disabled permanently? I get a nag screen on startup re component not loaded. I want it gone on my system!

Only a very small subset of people use this feature which is restricted to one manufacturer. I can think of about 3-4 regulars who do.

I think it would be much better if it was in the Plasmac Configuration section.

Please allow removal of all reference to it on main screen if the feature is not in use. Don't clutter the main screen with useless and irrelevant  information
I could not see any ini file settings to do this.

**Comment by phillc54** [comment]
Comment out the pm_port in the ini file. Same as it has always been. As stated in the readme this is not a working config, it is to give an idea of the look and feel.

**Comment by rodw-au** [comment]
Hmm, Commenting out that line generates an error:

Traceback (most recent call last):
  File "/home/rod/linuxcnc-dev/lib/python/qt5_graphics.py", line 661, in initializeGL
    self.realize()
  File "/home/rod/linuxcnc-dev/lib/python/qt5_graphics.py", line 455, in realize
    self.set_current_view()
  File "/home/rod/linuxcnc-dev/lib/python/qt5_graphics.py", line 512, in set_current_view
    return getattr(self, 'set_view_%s' % self.current_view)()
  File "/home/rod/linuxcnc-dev/lib/python/glnav.py", line 458, in set_view_z
    self.set_eyepoint_from_extents(size[0], size[1])
  File "/home/rod/linuxcnc-dev/lib/python/glnav.py", line 307, in set_eyepoint_from_extents
    ztran = max(2.0, e1, e2 * w/h) ** 2
ZeroDivisionError: integer division or modulo by zero

**Comment by phillc54** [comment]
Grr, I forgot to rename a frame. Fixed

**Comment by rodw-au** [comment]
Great. confirmed working
